export async function seed(knex) {
  await knex('bridges').insert([
    {
      name: 'Auckland Harbour Bridge',
      location: 'Auckland Harbour',
      type: 'Motorway bridge',
      year_built: 1959,
      length_meters: 'Unknown',
      lanes: 8,
      added_by_user: 'auth0|user1',
    },
    {
      name: 'Grafton Bridge',
      location: 'Grafton Gully',
      type: 'Road bridge',
      year_built: 'Unknown',
      length_meters: 'Unknown',
      lanes: 4,
      added_by_user: 'auth0|user2',
    },
    {
      name: 'Jacobs Ladder Bridge',
      location: 'Somewhere',
      type: 'Pedestrian bridge',
      year_built: 'Unknown',
      length_meters: 'Unknown',
      lanes: null,
      added_by_user: 'auth0|user3',
    },
    {
      name: 'Māngere Bridge',
      location: 'Māngere',
      type: 'Road bridge',
      year_built: 'Unknown',
      length_meters: 'Unknown',
      added_by_user: 'auth0|user4',
    },
    {
      name: 'Newmarket Viaduct',
      location: 'Newmarket',
      type: 'Viaduct',
      year_built: 'Unknown',
      length_meters: 'Unknown',
      added_by_user: 'auth0|user5',
    },
    {
      name: 'Onehunga Harbour Road Bridge',
      location: 'Onehunga Harbour Road',
      type: 'Road bridge',
      year_built: 'Unknown',
      length_meters: 'Unknown',
      lanes: 2,
      added_by_user: 'auth0|user6',
    },
    {
      name: 'Onepoto Bridge',
      location: 'Someplace',
      type: 'Bridge type',
      year_built: 'Unknown',
      length_meters: 'Unknown',
      added_by_user: 'auth0|user7',
    },
    {
      name: 'Panmure Bridge',
      location: 'Panmure',
      type: 'Bridge type',
      year_built: 'Unknown',
      length_meters: 'Unknown',
      added_by_user: 'auth0|user8',
    },
    {
      name: 'Tāmaki Bridge',
      location: 'Tāmaki',
      type: 'Bridge type',
      year_built: 'Unknown',
      length_meters: 'Unknown',
      added_by_user: 'auth0|user9',
    },
    {
      name: 'Upper Harbour Bridge',
      location: 'Upper Harbour',
      type: 'Bridge type',
      year_built: 'Unknown',
      length_meters: 'Unknown',
      added_by_user: 'auth0|user10',
    },
    {
      name: 'Victoria Park Viaduct',
      location: 'Victoria Park',
      type: 'Viaduct',
      year_built: 'Unknown',
      length_meters: 'Unknown',
      added_by_user: 'auth0|user11',
    },
    {
      name: 'Westgate Pedestrian and Cycle Bridge',
      location: 'Westgate',
      type: 'Pedestrian and Cycle Bridge',
      year_built: 'Unknown',
      length_meters: 'Unknown',
      added_by_user: 'auth0|user12',
    },
    {
      name: 'Wynyard Crossing',
      location: 'Wynyard Quarter',
      type: 'Bascule Bridge',
      year_built: 'Unknown',
      length_meters: 'Unknown',
      added_by_user: 'auth0|user13',
    },
  ])
}
